<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="SuiteXML" duration-ms="31" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:35Z">
    <groups>
      <group name="TestRun">
        <method signature="com.blade.tests.Tester.test1()" name="test1" class="com.blade.tests.Tester"/>
        <method signature="com.blade.tests.Tester.test2()" name="test2" class="com.blade.tests.Tester"/>
        <method signature="com.blade.tests.Tester.test3()" name="test3" class="com.blade.tests.Tester"/>
      </group>
    </groups>
    <test name="RegressionXML" duration-ms="31" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:35Z">
      <class name="com.blade.tests.Tester">
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="6" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="beforeMethod()" name="beforeMethod" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="test1()" name="test1" duration-ms="2" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="afterMethod()" name="afterMethod" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="beforeMethod()" name="beforeMethod" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="FAIL" signature="test2()" name="test2" duration-ms="1" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:480)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at com.blade.tests.Tester.test2(Tester.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.TestNG.privateMain(TestNG.java:1182)
	at org.testng.TestNG.main(TestNG.java:1146)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="afterMethod()" name="afterMethod" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="beforeMethod()" name="beforeMethod" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:34Z" finished-at="2011-12-13T23:17:34Z">
        </test-method>
        <test-method status="PASS" signature="test3()" name="test3" duration-ms="1" started-at="2011-12-13T23:17:35Z" finished-at="2011-12-13T23:17:35Z">
        </test-method>
        <test-method status="PASS" signature="afterMethod()" name="afterMethod" is-config="true" duration-ms="1" started-at="2011-12-13T23:17:35Z" finished-at="2011-12-13T23:17:35Z">
        </test-method>
        <test-method status="PASS" signature="tearDown()" name="tearDown" is-config="true" duration-ms="0" started-at="2011-12-13T23:17:35Z" finished-at="2011-12-13T23:17:35Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
